### PR TITLE
connect to sensord instead of accepting a connection from it

### PR DESCRIPTION
**Pull request by MaxKellermann**
For https://github.com/Openvario/sensord/issues/42 implemented by
https://github.com/Openvario/sensord/pull/43

### CODE REVIEW

**Comment by MaxKellermann** [comment]
The codacy warning is obviously bogus.

**Review by linuxianer99 — APPROVED** [review]
LGTM

**Comment by MaxKellermann** [comment]
I added the remaining patches waiting in my stack for this PR to be merged ...

**Comment by mihu-ov** [comment]
This means we can have XCSoar and variod connected to sensord simultaneously and just mute one, correct?

@linuxianer99 I talked to Andi a few days ago, he is busy with his house but still follows the messages here and is OK with modifying variod or retiring variod if the functions are included in XCSoar.

**Comment by MaxKellermann** [comment]
> This means we can have XCSoar and variod connected to sensord simultaneously and just mute one, correct?

No. This just reverses the connection between sensord and variod. This has nothing to do with XCSoar.

**Pull request merged**
