### PR TITLE
Introduce sensord simulator 

### LINKED ISSUE #23: Create automatic software tests for variod
Maybe we can use a framework like Robot framework https://robotframework.org/

### PR DESCRIPTION
**Pull request by kedder**
Allows to run variod locally on developer's machine and generate NMEA traffic for `variod`. Implemented with Python and documented in README.md

### CODE REVIEW

**Comment by kedder** [comment]
@linuxianer99, I think I fixed all the linter error that make sense. The rest are either conflicting (like https://app.codacy.com/gh/Openvario/variod/file/44822342475/issues/source?bid=18149062&fileBranchId=18150991#l9) or doesn't make sense to me (like docstring issues or "assert" thing).

In general, the linter is not very practical if I cannot run it locally on my machine. Takes too long to wait for each build to finish.

**Comment by linuxianer99** [comment]
Codacy is just a "collection" of different linters. 
So the python doc string is pep257 (https://pypi.org/project/pep257/) for example. 
You can also run this on a local machine i think.

I agree, that running on a local machine is better, but all actual "free" tools are web-based ..

**Comment by kedder** [comment]
Yes you can install those tools but they give different output, so that is not very useful.

**Comment by linuxianer99** [comment]
ok, that is strange ... should be the same ... hmmm...

**Comment by kedder** [comment]
I suspect codacity has some kind of implicit configuration that is not necesserily tool-default. If that configuration is not part of source code, it is not possible to match it.

**Comment by linuxianer99** [comment]
@kedder : Should we try to fix the Codacy issues ? Think most of them are just format things ...

**Comment by linuxianer99** [comment]
I tested a bit with the pep257. 
You are right ... it is awful !!
I disabled this checks in codacy ;-)

**Comment by kedder** [comment]
@linuxianer99, sorry, I was intended to write a detailed response after I get back from work, but in short: some of the checks are mutually exclusive. E.g. one of the check suggests I need to put 2 space indent before markdown list items, but when I do, another wants me to remove the indent. Similar thing with function docstrings.  I spent bunch of time trying to satisfy all checks, but it seems to be impossible in this default configuration.

Some of the checks made sense though. It basically needs to be tweaked. Default config is not very usable.

**Pull request merged**
